# Generated by Django 5.0.6 on 2026-08-18 07:44

import encrypted_model_fields.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='nrc',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='National Registration Card number (encrypted at rest)', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number in E.164 format', max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('transporter', 'Transporter'), ('admin', 'Administrator')], default='farmer', help_text="User's role in the system", max_length=20),
        ),
    ]
